insert into Jugador(nombre,capitulo,comienzoCap,puntos,preguntas) values('','C0','','0','2020-05-08 20:29:42');

insert into Dios(nombre, afinidad, info, rutaImg, mitologia) values ('Anubis',0,'Su sentido de la orientación puede guiarte hasta lo más profundo de la necrópolis. Anubis siempre taciturno y con aspecto desorientado es el más justo y objetivo de todos los dioses. Si necesitas un buen consejo, y lo encuentras de buen humor, este dios es el que estás buscando. ¡Siempre tiene vendas para que te puedas sonar los mocos!','drawable/anubis.png','egipcia');
insert into Dios(nombre, afinidad, info, rutaImg, mitologia) values ('Apolo',0,'Cuando no está cazando, está dando luz a sus plantas para crear pociones (o medicinas como dicen los humanos). En su tiempo libre compone, quién sabe, tal vez algún día te escriba a ti una canción. Lo que está claro es que cuando estás cerca suya un calor hogareño se apodera de tu piel, dejándote en un estado tranquilizador e inspirador que puede llevarte a crear cosas increíbles.','drawable/apolo.png','griega');
insert into Dios(nombre, afinidad, info, rutaImg, mitologia) values ('Dionisio',0,'No te dejes engañar por su aspecto juguetón y femenino, Dionisio es capaz de hacerte dudar de tal manera que querrás dejar de hacer cualquier cosa. Por lo demás, estar con él supone una fiesta continua además de que da las mejores celebraciones en el planeta. Todavía tiene peleas con Jesús sobre quien creó el bendito vino. Aunque no podamos estar seguros de quién fue, Dionisio es el que lleva una mundialmente famosa empresa de vinos y uvas; donde se le suele ver cuidando de sus campos.','drawable/dionisio.png','griega');
insert into Dios(nombre, afinidad, info, rutaImg, mitologia) values ('Freya',0,'Freya no le teme a casi nada, es valiente, testaruda y decidida. Puede parecer un solitaria pero se llevó tal susto cuando creyó que perdía a todos sus compañeros que ahora evita encariñarse con nadie para que no le vuelva a pasar. Suele estar retirada en el monte donde entrena a las jovencitas (aunque se hacen llamar valkirias) que se apuntan a su campamento. No te recomendamos meterte en su camino, es capaz de hacer lo que sea por conseguir sus propósitos.','drawable/freya.png','nordica');
insert into Dios(nombre, afinidad, info, rutaImg, mitologia) values ('Hermes',0,'Aunque ha dejado de ser el mensajero de todos los dioses con su trabajo de patrocinador de la bebida energética MythsUp hace llegar sus ideas a los jóvenes en las redes sociales. Apenas tiene días de descanso, si no fuera por las cantidades industriales de maquillaje que le hacen utilizar parecería una de las momias de Anubis o Isis. Aunque esté agotado, está orgulloso de ser un modelo a seguir para todas aquellas almas que están perdidas.','drawable/hermes.png','griega');
insert into Dios(nombre, afinidad, info, rutaImg, mitologia) values ('Isis',0,'Todo en ella llama la atención, su eyeliner perfecto, sus sombreros estrambóticos, la inmensa preocupación que tiene por su hijo, que sea capaz de resucitar muertos… Algunos la llaman la Diosa de la vida, ¿Será ella la madre de Pinocho?','drawable/isis.png','egipcia');
insert into Dios(nombre, afinidad, info, rutaImg, mitologia) values ('Loki',0,'Quien diría que el famoso Loki está lleno de inseguridades y baja autoestima. No encuentra su lugar en el mundo, además de sentirse apartado por sus compañeros. A todos esto nos resulta raro porque es astuto e ingenioso a niveles inimaginables. Sigue haciendo favores, pero por un precio justo. De todas maneras, de lo que más disfruta es ayudar a Freya en su campamento enseñando hípica. ¡ Para montar en caballo, tienes que sentir el caballo, tienes que ser el caballo!','drawable/loki.png','nordica');
insert into Dios(nombre, afinidad, info, rutaImg, mitologia) values ('Iv',0,'Ivinfo','IvImfruta','none');

insert into Capitulo (codigo, nombre, rutaFic, hecho) values ('1','','raw.C1',0);
insert into Capitulo (codigo, nombre, rutaFic, hecho) values ('1.1','','raw.C1',0);
insert into Capitulo (codigo, nombre, rutaFic, hecho) values ('1.2','','raw.C1',0);
insert into Capitulo (codigo, nombre, rutaFic, hecho) values ('1.3','','raw.C1',0);
insert into Capitulo (codigo, nombre, rutaFic, hecho) values ('2','','raw.C2',0);
insert into Capitulo (codigo, nombre, rutaFic, hecho) values ('2.1','','raw.C3',0);
insert into Capitulo (codigo, nombre, rutaFic, hecho) values ('2.2','','raw.C3',0);
insert into Capitulo (codigo, nombre, rutaFic, hecho) values ('3','','raw.C4',0);

insert into MegaEleccion (decision, hecha, rutaFic) values ('d1',0,'raw.d1');
